[package]
name = "rust_wasmedge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmedge-sys = "0.7.0"
wasmedge-types = "0.1.3"